Add udp echo test controller
Azure/DaaS pull request #10
Opened 2021-05-13 21:22 UTC by yifguoMSFT

Add udp echo test controller to DaaS extension to allow doing UDP ping test between instances via VNet

2021-05-23 03:05 UTC, puneetg1983 requested changes

2021-06-03 16:51 UTC, yifguoMSFT commented on DiagnosticsExtension/Controllers/UdpEchoTestController.cs
> +                        IPEndPoint RemoteIpEndPoint = new IPEndPoint(IPAddress.Any, 0);
removed

2021-06-03 16:51 UTC, yifguoMSFT commented on DiagnosticsExtension/Controllers/UdpEchoTestController.cs
> +            int port = 30000;
This is specified for pinging a worker instance at port 30000, on which the instance is running an udp echo server.

2021-06-03 16:54 UTC, puneetg1983 approved these changes

2021-06-03 16:55 UTC, merged